import z from 'zod';
export declare const hitpayConstructorSchema: z.ZodObject<{
    apiKey: z.ZodString;
    apiSalt: z.ZodString;
    environment: z.ZodUnion<[z.ZodLiteral<"sandbox">, z.ZodLiteral<"production">]>;
}, "strip", z.ZodTypeAny, {
    apiKey: string;
    apiSalt: string;
    environment: "sandbox" | "production";
}, {
    apiKey: string;
    apiSalt: string;
    environment: "sandbox" | "production";
}>;
export declare const createPaymentParamsSchema: z.ZodObject<{
    amount: z.ZodNumber;
    payment_methods: z.ZodOptional<z.ZodArray<z.ZodString, "many">>;
    currency: z.ZodString;
    email: z.ZodOptional<z.ZodString>;
    purpose: z.ZodOptional<z.ZodString>;
    name: z.ZodOptional<z.ZodString>;
    phone: z.ZodOptional<z.ZodString>;
    reference_number: z.ZodOptional<z.ZodString>;
    redirect_url: z.ZodOptional<z.ZodString>;
    webhook: z.ZodOptional<z.ZodString>;
    allow_repeated_payments: z.ZodOptional<z.ZodBoolean>;
    expiry_date: z.ZodOptional<z.ZodString>;
    send_email: z.ZodOptional<z.ZodBoolean>;
    send_sms: z.ZodOptional<z.ZodBoolean>;
    expires_after: z.ZodOptional<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    amount: number;
    currency: string;
    payment_methods?: string[] | undefined;
    email?: string | undefined;
    purpose?: string | undefined;
    name?: string | undefined;
    phone?: string | undefined;
    reference_number?: string | undefined;
    redirect_url?: string | undefined;
    webhook?: string | undefined;
    allow_repeated_payments?: boolean | undefined;
    expiry_date?: string | undefined;
    send_email?: boolean | undefined;
    send_sms?: boolean | undefined;
    expires_after?: string | undefined;
}, {
    amount: number;
    currency: string;
    payment_methods?: string[] | undefined;
    email?: string | undefined;
    purpose?: string | undefined;
    name?: string | undefined;
    phone?: string | undefined;
    reference_number?: string | undefined;
    redirect_url?: string | undefined;
    webhook?: string | undefined;
    allow_repeated_payments?: boolean | undefined;
    expiry_date?: string | undefined;
    send_email?: boolean | undefined;
    send_sms?: boolean | undefined;
    expires_after?: string | undefined;
}>;
export declare const createPaymentSuccessSchema: z.ZodObject<{
    id: z.ZodString;
    name: z.ZodString;
    email: z.ZodString;
    phone: z.ZodString;
    amount: z.ZodString;
    currency: z.ZodString;
    status: z.ZodString;
    purpose: z.ZodString;
    reference_number: z.ZodString;
    payment_methods: z.ZodArray<z.ZodString, "many">;
    url: z.ZodString;
    redirect_url: z.ZodString;
    webhook: z.ZodString;
    send_sms: z.ZodBoolean;
    send_email: z.ZodBoolean;
    sms_status: z.ZodString;
    email_status: z.ZodString;
    allow_repeated_payments: z.ZodBoolean;
    expiry_date: z.ZodString;
    created_at: z.ZodString;
    updated_at: z.ZodString;
}, "strip", z.ZodTypeAny, {
    email: string;
    url: string;
    status: string;
    amount: string;
    payment_methods: string[];
    currency: string;
    purpose: string;
    name: string;
    phone: string;
    reference_number: string;
    redirect_url: string;
    webhook: string;
    allow_repeated_payments: boolean;
    expiry_date: string;
    send_email: boolean;
    send_sms: boolean;
    id: string;
    sms_status: string;
    email_status: string;
    created_at: string;
    updated_at: string;
}, {
    email: string;
    url: string;
    status: string;
    amount: string;
    payment_methods: string[];
    currency: string;
    purpose: string;
    name: string;
    phone: string;
    reference_number: string;
    redirect_url: string;
    webhook: string;
    allow_repeated_payments: boolean;
    expiry_date: string;
    send_email: boolean;
    send_sms: boolean;
    id: string;
    sms_status: string;
    email_status: string;
    created_at: string;
    updated_at: string;
}>;
